import "./globals.css";
import ReduxProvider from "../../lib/ReduxProvider";
import WhatsAppButton from "@/components/btnWhatsapp/ButtonWhatsapp";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReduxProvider>
        <WhatsAppButton />
      </body>
    </html>
  );
}
